### ISSUE TITLE
Cannot find local.xml.phpunit file in app/etc directory

### ISSUE THREAD

**Issue by jameswithers** [EcomDev/EcomDev_PHPUnit#217]
composer.json:

``` javascript
{
    "require-dev": {
        "ecomdev/ecomdev_phpunit": "*",
        "magento-hackathon/magento-composer-installer": "*"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.firegento.com"
        }
    ],
    "extra":{
        "magento-root-dir": ".",
        "magento-deploystrategy": "copy"
    }
}
```

In `$root/shell/`:
`php -f ecomdev-phpunit.php -- -a magento-config --db-user ...`
and I get:
`Cannot find local.xml.phpunit file in app/etc directory`
because it's missing.

**Comment by torrtuga** [comment]
@IvanChepurnyi 
I know its been more than 5 years, but I am having the same issue.
And can you please tell what is original/module/dir in this context?

**Comment by IvanChepurnyi** [comment]
@torrtuga hard to remember, but I think it is EcomDev_PHPUnit module path...

**Comment by torrtuga** [comment]
> @torrtuga hard to remember, but I think it is EcomDev_PHPUnit module path...
Thanks for the reply.
Yeah it worked for me running the command` php -f ecomdev-phpunit.php -- --action install` from `shell` folder.

I have a query regarding the internals of EcomDev. When we try to setup for a big magento project, then  we are copying a huge database to our test database. 

In my case when during the installation time (3rd step), it tries to run one of the mysql-upgrade file of the project and throws an error (`Base table or view not found: 1146 Table 'magento_test.customer_entity' doesn't exist, query was: DESCRIBE `customer_entity` in /var/www/html/fresh/app/Mage.php:580`).

What I am thinking is it could be because of trying to run the mysql script before another script which is supposed to be run, because of which it could not find a particular entity). I could be wrong also.

So, is there any way to resolve this particular issue?
